// Minimal fetch wrapper for the content-stack daemon REST API.
//
// Per PLAN.md D5 every authenticated REST + MCP request requires
//   Authorization: Bearer <token>
// The token is generated by the daemon at first launch and lives at
// ~/.local/state/content-stack/auth.token (mode 0600).
//
// TODO(M3): The full plumbing is to fetch the bearer token from a
// dedicated endpoint such as `GET /api/v1/auth/ui-token` (whitelisted
// for the same-origin UI) and persist it in memory for the session,
// or have the daemon set a same-site cookie on first GET / load.
// Neither endpoint exists yet at M0; for now callers may pass an
// explicit `init.token` and the wrapper will attach the header.
//
// The /api/v1/health endpoint that HomeView pings at M0 is whitelisted
// so it does NOT need a token.

export type ApiInit = RequestInit & { token?: string }

export class ApiError extends Error {
  status: number
  body: unknown
  constructor(message: string, status: number, body: unknown) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.body = body
  }
}

const API_BASE: string = import.meta.env.VITE_API_BASE ?? ''

function buildUrl(path: string): string {
  if (path.startsWith('http://') || path.startsWith('https://')) return path
  const base = API_BASE.replace(/\/$/, '')
  const suffix = path.startsWith('/') ? path : `/${path}`
  return `${base}${suffix}`
}

export async function apiFetch<T = unknown>(path: string, init: ApiInit = {}): Promise<T> {
  const { token, headers, ...rest } = init
  const finalHeaders: Record<string, string> = {
    Accept: 'application/json',
    ...(headers as Record<string, string> | undefined),
  }
  if (token) {
    finalHeaders.Authorization = `Bearer ${token}`
  }

  const res = await fetch(buildUrl(path), { ...rest, headers: finalHeaders })
  const contentType = res.headers.get('content-type') ?? ''
  const isJson = contentType.includes('application/json')
  const body = isJson ? await res.json().catch(() => null) : await res.text()

  if (!res.ok) {
    throw new ApiError(`Request to ${path} failed with ${res.status}`, res.status, body)
  }
  return body as T
}
