// Fetch wrapper for the content-stack daemon REST API.
//
// Per PLAN.md D5 every authenticated REST + MCP request requires
//   Authorization: Bearer <token>
// The token is generated by the daemon at first launch and lives at
// ~/.local/state/content-stack/auth.token (mode 0600).
//
// The browser cannot read that file directly — it bootstraps the token
// at app boot via `GET /api/v1/auth/ui-token` (whitelisted, same-origin
// + Host-loopback enforced server-side; see docs/security.md). The
// `useAuthStore().bootstrap()` Pinia call performs the fetch and the
// fetch wrapper here pulls the in-memory token off the store on every
// request.
//
// 401 responses ⇒ surface to the caller, who is expected to redirect to
// the auth-error route. We deliberately DO NOT auto-retry on 401 to
// avoid masking a real auth failure.
//
// 412 (If-Match precondition failed) is left for the caller — the
// MarkdownEditor handles it specially by prompting the user to reload
// or overwrite the remote change.

import type { AuthStoreLike } from '@/stores/auth-store-shape'

export type ApiInit = RequestInit & { token?: string }

export class ApiError extends Error {
  status: number
  body: unknown
  constructor(message: string, status: number, body: unknown) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.body = body
  }
}

const API_BASE: string = import.meta.env.VITE_API_BASE ?? ''

// The auth store is wired in at app-bootstrap time via `setAuthStore`. We
// avoid importing the Pinia store directly here so the client module stays
// usable from places that haven't called `app.use(pinia)` yet (e.g. early
// bootstrap, pre-pinia tests). The runtime contract: `setAuthStore` must
// be called before any authenticated `apiFetch` lands.
let _authStore: AuthStoreLike | null = null

export function setAuthStore(store: AuthStoreLike): void {
  _authStore = store
}

export function clearAuthStore(): void {
  _authStore = null
}

function buildUrl(path: string): string {
  if (path.startsWith('http://') || path.startsWith('https://')) return path
  const base = API_BASE.replace(/\/$/, '')
  const suffix = path.startsWith('/') ? path : `/${path}`
  return `${base}${suffix}`
}

export async function apiFetch<T = unknown>(path: string, init: ApiInit = {}): Promise<T> {
  const { token: explicitToken, headers, ...rest } = init
  const finalHeaders: Record<string, string> = {
    Accept: 'application/json',
    ...(headers as Record<string, string> | undefined),
  }
  // Explicit token wins (used by tests + the bootstrap probe itself).
  // Otherwise pull from the auth store if it's been wired up.
  const token = explicitToken ?? _authStore?.token ?? null
  if (token) {
    finalHeaders.Authorization = `Bearer ${token}`
  }

  const res = await fetch(buildUrl(path), { ...rest, headers: finalHeaders })
  const contentType = res.headers.get('content-type') ?? ''
  const isJson = contentType.includes('application/json')
  const body = isJson ? await res.json().catch(() => null) : await res.text()

  if (!res.ok) {
    throw new ApiError(`Request to ${path} failed with ${res.status}`, res.status, body)
  }
  return body as T
}

/**
 * Convenience wrapper for endpoints that return the standard `WriteResponse<T>`
 * envelope (`{ data, etag, updated_at }`). Returns the inner data so call
 * sites can ignore the envelope when they don't need it.
 */
export async function apiWrite<T = unknown>(path: string, init: ApiInit = {}): Promise<T> {
  const env = await apiFetch<{ data: T; etag?: string; updated_at?: string }>(path, init)
  return env.data
}
