"""Agent-facing MCP bridge tool surface constants."""

from __future__ import annotations

from stackos.workflows.run_plan_grants import (
    RUN_PLAN_ADMIN_ONLY_TOOL_NAMES,
    RUN_PLAN_CONTROLLER_TOOL_NAMES,
    RUN_PLAN_GRANTABLE_TOOL_NAMES,
)

_AGENT_VISIBLE_TOOL_ORDER: tuple[str, ...] = (
    "workspace.startSession",
    "workspace.resolve",
)
_AGENT_VISIBLE_TOOL_NAMES = frozenset(_AGENT_VISIBLE_TOOL_ORDER)
_AGENT_COMPACT_DEFAULT_TOOL_NAMES: frozenset[str] = frozenset(
    {
        "workspace.startSession",
        "workspace.resolve",
        "workspace.bootstrap",
        "workspace.connect",
        "auth.status",
        "toolProfile.resolve",
        "agentPreset.resolveForWorkflow",
        "ingressEndpoint.routes",
        "ingressEndpoint.status",
        "communicationProfile.list",
        "communicationProfile.get",
        "communicationTarget.list",
        "communicationTarget.resolve",
        "tracker.status",
        "tracker.next",
        "tracker.brief",
        "tracker.verify",
        "action.describe",
        "action.list",
        "integration.list",
        "catalog.describe",
    }
)
_AGENT_RESPONSE_MODE_FIELD = "response_mode"
_AGENT_GLOBAL_DISCOVERY_TOOL_NAMES: frozenset[str] = frozenset(
    {
        "workspace.startSession",
        "workspace.resolve",
        "workspace.bootstrap",
        "workspace.connect",
        "workspace.listBindings",
        "project.list",
        "project.get",
        "project.create",
        "plugin.list",
        "catalog.list",
        "catalog.describe",
        "capability.list",
        "capability.describe",
        "provider.list",
        "provider.describe",
        "operation.list",
        "operation.describe",
        "action.describe",
        "action.list",
        "action.validate",
        "integration.list",
        "agentPreset.list",
        "agentPreset.describe",
        "agentPreset.resolveForWorkflow",
        "meta.enums",
    }
)
_TOOLBOX_DESCRIBE_TOOL = "toolbox.describe"
_TOOLBOX_CALL_TOOL = "toolbox.call"
_TOOLBOX_TOOL_NAMES = frozenset({_TOOLBOX_DESCRIBE_TOOL, _TOOLBOX_CALL_TOOL})
_AGENT_ADMIN_GATED_TOOL_NAMES: frozenset[str] = frozenset(RUN_PLAN_ADMIN_ONLY_TOOL_NAMES)
_AGENT_RUN_PLAN_GATED_TOOL_NAMES: frozenset[str] = frozenset(RUN_PLAN_GRANTABLE_TOOL_NAMES)
_AGENT_STEP_GATED_TOOL_NAMES: frozenset[str] = frozenset(RUN_PLAN_CONTROLLER_TOOL_NAMES)
_AGENT_GATED_TOOL_NAMES: frozenset[str] = (
    _AGENT_ADMIN_GATED_TOOL_NAMES | _AGENT_RUN_PLAN_GATED_TOOL_NAMES
)

# Tools that stay out of the advertised MCP list but are still useful during
# setup when an agent explicitly asks the bridge to describe/call them.
_AGENT_SETUP_TOOLBOX_NAMES: frozenset[str] = frozenset(
    {
        "action.describe",
        "action.list",
        "action.run",
        "action.validate",
        "integration.list",
        "agentPreset.describe",
        "agentPreset.list",
        "agentPreset.resolveForWorkflow",
        "agentRequest.claim",
        "agentRequest.complete",
        "agentRequest.get",
        "agentRequest.ignore",
        "agentRequest.linkRunPlan",
        "agentRequest.list",
        "agentRequest.prepareRunPlan",
        "agentRequest.release",
        "artifact.get",
        "artifact.query",
        "auth.status",
        "auth.test",
        "budget.list",
        "budget.queryProject",
        "budget.set",
        "budget.update",
        "catalog.describe",
        "catalog.list",
        "capability.describe",
        "capability.list",
        "communication.reply",
        "communication.send",
        "communicationContact.list",
        "communicationContact.upsert",
        "communicationContext.query",
        "communicationMembership.list",
        "communicationMembership.upsert",
        "communicationProfile.get",
        "communicationProfile.list",
        "communicationProfile.upsert",
        "communicationRoute.list",
        "communicationRoute.upsert",
        "communicationSurface.list",
        "communicationSurface.upsert",
        "communicationTarget.list",
        "communicationTarget.resolve",
        "communicationTarget.upsert",
        "context.query",
        "context.timeline",
        "cost.queryAll",
        "cost.queryProject",
        "decision.query",
        "experiment.query",
        "ingressEndpoint.configure",
        "ingressEndpoint.refresh",
        "ingressEndpoint.routes",
        "ingressEndpoint.status",
        "ingressEndpoint.sync",
        "learning.query",
        "localAgentChat.createMessage",
        "meta.enums",
        "operation.describe",
        "operation.list",
        "plugin.list",
        "readiness.check",
        "project.create",
        "project.get",
        "project.list",
        "provider.describe",
        "provider.list",
        "resource.get",
        "resource.query",
        "run.abort",
        "run.children",
        "run.cost",
        "run.finish",
        "run.get",
        "run.heartbeat",
        "run.insertStep",
        "run.list",
        "run.listStepCalls",
        "run.listSteps",
        "run.recordStepCall",
        "run.start",
        "runPlan.abort",
        "runPlan.checkConsistency",
        "runPlan.create",
        "runPlan.get",
        "runPlan.list",
        "runPlan.recover",
        "runPlan.reopen",
        "runPlan.start",
        "runPlan.validate",
        "schedule.list",
        "schedule.remove",
        "schedule.set",
        "schedule.toggle",
        "sitemap.fetch",
        "toolProfile.resolve",
        "tracker.blockers",
        "tracker.brief",
        "tracker.changed",
        "tracker.createTask",
        "tracker.createTicket",
        "tracker.execute",
        "tracker.get",
        "tracker.history",
        "tracker.linkRunPlan",
        "tracker.next",
        "tracker.patch",
        "tracker.pick",
        "tracker.rejectTask",
        "tracker.reopen",
        "tracker.release",
        "tracker.search",
        "tracker.status",
        "tracker.updateTask",
        "tracker.updateTicket",
        "tracker.verify",
        "tracker.why",
        "workflowExtension.get",
        "workflowExtension.list",
        "workflowExtension.delete",
        "workflowExtension.upsert",
        "workflowExtension.validate",
        "workflowTemplate.describe",
        "workflowTemplate.list",
        "workflowTemplate.validate",
        "workspace.bootstrap",
        "workspace.connect",
        "workspace.listBindings",
        "workspace.updateProfile",
    }
)
_AGENT_BASE_TOOLBOX_NAMES = _AGENT_VISIBLE_TOOL_NAMES | _AGENT_SETUP_TOOLBOX_NAMES
